version: "3.8"

services:
  db:
    image: postgres:14
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init_data:/docker-entrypoint-initdb.d
    ports:
      - '5432'

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    command: serve

  web:
    image: node:lts
    user: 'root'
    working_dir: /repository
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
      - ollama
      - python-api
    ports:
      - '3000:3000'
    volumes:
      - ./:/repository
    command: sh -c "npm install && npm run start"

    python-api:
     build:
       context: ./python_api
     ports:
       - '5001:5001'
    restart: unless-stopped

volumes:
  db-data:
  ollama-data: