services:
  db:
    image: postgres:14
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init_data:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  ollama:
    build:
      context: .
      dockerfile: ollama.Dockerfile
    volumes:
      - ollama-data:/root/.ollama
      - ./ollama-entrypoint.sh:/entrypoint.sh  # ✅ mount it
    ports:
      - "11434:11434"
    entrypoint: /entrypoint.sh  # ✅ correct name and path



  web:
    image: node:lts
    user: 'root'
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - '3000:3000'
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
      - ollama
      # - python-api
    command: sh -c "npm install && npm run start"

  python-api:
    build:
      context: ./python_api
    ports:
      - '5001:5001'
    restart: unless-stopped

volumes:
  db-data:
  ollama-data: