services:
  db:
    image: postgres:14
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init_data:/docker-entrypoint-initdb.d
    ports:
      - '5432'

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    # Using just "serve" as the command since the entrypoint is already set to "ollama"
    command: serve

  web:
    image: node:lts
    user: 'node'
    working_dir: /repository
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
      - ollama
    ports:
      - '3000:3000'
    volumes:
      - ./:/repository
    command: 'npm run start'
volumes:
  db-data:
  ollama-data:

